name: py3-sphinx
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - asn1crypto=1.2.0
  - babel=2.7.0
  - ca-certificates=2019.11.28
  - cairo=1.14.6
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - cryptography=2.8
  - docutils=0.15.2
  - fontconfig=2.12.1
  - freetype=2.7
  - gettext=0.19.8.1
  - glib=2.51.4
  - gmp=6.1.2
  - icu=58.2
  - idna=2.8
  - imagesize=1.1.0
  - jinja2=2.10.3
  - latexcodec=1.0.7
  - latexmk=4.55
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libiconv=1.15
  - libpng=1.6.37
  - libstdcxx-ng=9.2.0
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - mpfr=4.0.2
  - ncurses=6.1
  - openssl=1.1.1d
  - oset=0.1.3
  - packaging=19.2
  - pcre=8.43
  - perl=5.20.3.1
  - pip=19.3.1
  - pixman=0.34.0
  - pybtex=0.22.2
  - pybtex-docutils=0.2.2
  - pycparser=2.19
  - pygments=2.5.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.5
  - pysocks=1.7.1
  - python=3.8.0
  - pytz=2019.3
  - pyyaml=5.2
  - readline=8.0
  - requests=2.22.0
  - setuptools=42.0.2
  - six=1.13.0
  - snowballstemmer=2.0.0
  - sphinx=2.2.2
  - sphinx_bootstrap_theme=0.6.4
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-bibtex=1.0.0
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - sqlite=3.30.1
  - texlive-core=20160523b
  - tk=8.6.10
  - urllib3=1.25.7
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11

